// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"database/sql"
	"time"
)

type Permission struct {
	RoleID       int32
	Visualizet   bool
	Createt      bool
	Readt        bool
	Updatet      bool
	Deletet      bool
	VisualizeAll bool
	DeleteAll    bool
}

type Role struct {
	ID   sql.NullInt32
	Name string
}

type Task struct {
	ID          int32
	UserID      int32
	Title       string
	Description string
	CreatedAt   time.Time
	CompletedAt sql.NullTime
}

type User struct {
	ID   int32
	Name string
	Role string
}
